apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-zpbr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-zpbr
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-zpbr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-zpbr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-zpbr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tnvj-tenant/nodejs-users/simple-nodejs-app-zpbr@sha256:563aa3356d83a2c33b18a9b572c9edf93e2df463cd726ab36284921111e16511
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
